language: r
cache: packages
latex: true
r_packages: 
  - bench
r_github_packages:
  - r-lib/covr
before_install:
  - sudo apt-get update
  - sudo apt-get install libmagic-dev
before_script:
 - Rscript -e "keras::install_keras()"
after_success:
  - Rscript -e 'covr::codecov()'